builds:
  -
    id: amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}_checksums.txt"
