builds:
  -
    id: amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64_checksum.txt"
