builds:
  -
    id: arm64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

release:
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_linux_arm64_checksum.txt"
