name: goreleaser

on: 
  release:
    types: [created]

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
        include:
          # specify the config file id to be executed for each different OS
          - os: ubuntu-latest
            build_id: "amd64"
          - os: ARM64
            build_id: "arm64"

    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f .goreleaser.${{ matrix.build_id }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
