name: goreleaser

on: 
  release:
    types: [created]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        - uses: actions/github-script@v4
          with:
            script: |
              const os = require('os')
              console.log(os.platform(), os.arch())
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
